### ISSUE TITLE
PacMan animation failed

### ISSUE THREAD

**Issue by misterfifi1** [Rogero0o/PasswordLoadingView#2]
Hi, 

There is an issue when the password is too long

Regards,

**Comment by Rogero0o** [comment]
Roger that~ Thanks,i will fix it soon.

**Comment by misterfifi1** [comment]
Hi, 

Thanks for your quick reply, it seems to be difficult to reproduce the bug, but for info, my code was following this process: 
- The field is automatically set if something is previously saved 
- The password is long as 11 characters, ended by @ 

Regards,

**Comment by Rogero0o** [comment]
Can't reproduce it..
